version: "3.8"

services:
  app:
    build: .
    container_name: app-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-php

networks:
  app-php:
    driver: bridge